import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Vehicle Sale Purchase Doc Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap" rel="stylesheet" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <h1>Vehicle Sale Purchase Doc Generator</h1>
          <p>sale receipt, transfer letter and delivery letter generator application built with ❤️ using nextjs</p>
          <Link class="btn btn-primary" href="/">Get Started</Link>
        </div>
      </main>
    </>
  )
}
